# Generated by Django 5.1.4 on 2025-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(default='no ingredients yet')),
                ('cooking_time', models.PositiveIntegerField()),
                ('difficutly', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Meduim'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20)),
            ],
        ),
    ]
