# Generated by Django 5.1.4 on 2025-01-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='difficutly',
            new_name='difficulty',
        ),
    ]
