# Generated by Django 5.1.4 on 2025-02-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
    ]
