# Generated by Django 5.1.4 on 2025-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipe_ingredients", "0001_initial"),
        ("recipes", "0008_remove_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="new_ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipe_ingredients.RecipeIngredient",
                to="ingredients.ingredient",
            ),
        ),
    ]
