# Generated by Django 5.1.4 on 2025-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_rename_new_ingredients_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(max_length=20),
        ),
    ]
