# Generated by Django 4.2.19 on 2025-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_picture.webp", upload_to="recipes"),
        ),
    ]
